### ISSUE TITLE
Issue when executing AzureBatchWebJob

### ISSUE THREAD

**Issue by SanjeevKumar300** [Azure/cortana-intelligence-energy-supply-optimization#3]
Hi,
    I had followed the step-by-step instructions in the Manual Deployment Guide was able to successful execute all the steps until this execution failed in this job. Here is the snapshot of the error from the log window. Not sure what is the problem? Would be helpful to resolve the issue so that the solution implementation can be complete

[04/28/2020 03:33:27 > 74a006: SYS INFO] Status changed to Starting
[04/28/2020 03:33:27 > 74a006: SYS INFO] WebJob singleton setting is True
[04/28/2020 03:33:27 > 74a006: SYS INFO] WebJob singleton lock is acquired
[04/28/2020 03:33:28 > 74a006: SYS INFO] Run script 'webjob_trigger.py' with script host - 'PythonScriptHost'
[04/28/2020 03:33:28 > 74a006: SYS INFO] Status changed to Running
[04/28/2020 03:33:32 > 74a006: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[04/28/2020 03:33:32 > 74a006: SYS INFO] Status changed to Stopping
[04/28/2020 03:33:38 > 74a006: ERR ] Thread was being aborted.
[04/28/2020 03:33:38 > 74a006: SYS INFO] WebJob process was aborted
[04/28/2020 03:33:38 > 74a006: SYS INFO] Status changed to Stopped
[04/28/2020 03:33:38 > 74a006: SYS INFO] WebJob singleton lock is released
[04/28/2020 03:33:38 > 74a006: SYS INFO] Status changed to Starting
[04/28/2020 03:33:38 > 74a006: SYS INFO] WebJob singleton lock is acquired
[04/28/2020 03:33:38 > 74a006: SYS INFO] Run script 'webjob_trigger.py' with script host - 'PythonScriptHost'
[04/28/2020 03:33:38 > 74a006: SYS INFO] Status changed to Running
[04/28/2020 03:33:47 > 74a006: INFO] Program start: 2020-04-28 03:33:46
[04/28/2020 03:33:47 > 74a006: INFO] ()
[04/28/2020 03:33:47 > 74a006: INFO] checking input queue
[04/28/2020 03:33:47 > 74a006: ERR ] No handlers could be found for logger "msrest.pipeline.requests"
[04/28/2020 03:33:47 > 74a006: INFO] preparing for input storage...
[04/28/2020 03:33:47 > 74a006: INFO] creating batch client...
[04/28/2020 03:33:47 > 74a006: INFO] assembling job scripts...
[04/28/2020 03:33:47 > 74a006: ERR ] Traceback (most recent call last):
[04/28/2020 03:33:47 > 74a006: INFO] creating pool...
[04/28/2020 03:33:47 > 74a006: ERR ]   File "webjob_trigger.py", line 281, in <module>
[04/28/2020 03:33:47 > 74a006: INFO] Creating pool [derciqspool1588044826]...
[04/28/2020 03:33:47 > 74a006: ERR ]   File "webjob_trigger.py", line 92, in create_pool
[04/28/2020 03:33:47 > 74a006: ERR ]     batch_service_client, publisher, offer, sku)
[04/28/2020 03:33:47 > 74a006: ERR ]   File "D:\local\Temp\jobs\continuous\AzureBatchWebJob\njopod3n.vhp\common\helpers.py", line 89, in select_latest_verified_vm_image_with_node_agent_sku
[04/28/2020 03:33:47 > 74a006: ERR ]     sku_to_use, image_ref_to_use = skus_to_use[0]
[04/28/2020 03:33:47 > 74a006: ERR ] IndexError: list index out of range
[04/28/2020 03:33:47 > 74a006: SYS ERR ] Job failed due to exit code 1
[04/28/2020 03:33:47 > 74a006: SYS INFO] Process went down, waiting for 60 seconds

**Comment by imcdnzl** [comment]
I see your PR #4 and I've just been made maintainer. I will check when I have time and then hopefully merge.
